students=["Sagar","Avinash","Chetan"]
print(students)
print(students[0])
print(students[-1])
print(students[-3:-1])
students.append("Trupti")
students.insert(1,"Diya")
students.remove("Trupti")
print(students)
students.sort()
print(students)
students.reverse()
print(students)
len(students)
['Sagar','Avinash','Chetan']
['Sagar','Avinash']
['Sagar','Vikas','Avinash','Chetan']
['Avinash','Chetan','Vikas','Sagar']
['Sagar','Vikas','Chetan','Avinash']
4
course=("python",3,12500,12500)
print(course[1])
print(course[-1])
print(course[-1:2])
print(course.count(12500))
print(course.index(3))
print(course)
cou=list(course)
cou.pop()
course=tuple(cou)
print(course)


#dictonary
employees={
    1001:"Ramesh",1002:"Suresh",1003:"Rajesh"}
print(employees)
print(employees[1003])
print(employees.keys())
print(employees.values())
employees[1005]="Radhika"
employees[1001]='Rakesh'
employees[1005]='Rakesh'
print(employees)
len(employees)

